<?php
declare (strict_types = 1);

namespace app\admin\controller;

use think\Request;
use app\common\controller\AdminController;
use app\common\model\Admin as AdminModel;

class Admin extends AdminController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model = AdminModel::class;
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        return $this->view->fetch();
    }

    public function getAdminList()
    {
        if ($this->request->isAjax()) {
            $page = (int) $this->request->param('page', 1);
            $limit = (int) $this->request->param('limit', 10);
            $username = $this->request->param('username', '');
            $map = [];

            if ($username) {
                $map[] = ['username', 'like', '%' . $username . '%'];
            }

            $this->returnData['code'] = 1;
            $this->returnData['total'] = $this->model::where($map)->count();
            $this->returnData['data'] = $this->model::where($map)
                ->withCount(['house'])
                ->order('id desc, login_time desc')
                ->limit(($page - 1) * $limit, $limit)
                ->select();

            $this->success(lang('Done'));
        }

        $this->error();
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        return $this->view->fetch('admin/add');
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        if ($this->request->isPost()) {
            $params = $request->param();
            $params['username'] = trim($params['username']);
            $params['password'] = password_hash(trim($params['password']), PASSWORD_BCRYPT);

            if ($this->model::getByUsername($params['username'])) {
                $this->returnData['msg'] = '用户已经存在';
                return json($this->returnData);
            }

            if (!empty($params['phone']) && $this->model::getByPhone($params['phone'])) {
                $this->error('手机号已经存在');
            }

            $userModel = new $this->model();

            if ($userModel->save($params)) {
                $this->returnData['msg'] = '开通成功';
                $this->returnData['code'] = 1;
            } else {
                $this->returnData['msg'] = '开通失败';
            }

            $this->success();
        }

        $this->error();
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        $this->view->assign('admin', $this->model::find($id));
        return $this->view->fetch();
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->isPost()) {
            $params = $request->only(['username', 'password', 'phone', 'status']);
            $admin = $this->model::find($id);
            $this->returnData['data'] = $params['password'];
            if ($admin->password !== $params['password']) {
                $params['password'] = password_hash(trim($params['password']), PASSWORD_BCRYPT);
            }
            $admin->save($params);
            $this->returnData['code'] = 1;
            $this->success(lang('Done'));
        }

        $this->error();
    }

    public function profile()
    {
        return $this->view->fetch('user/profile');
    }

    public function resetPassword()
    {
        if ($this->request->isPost()) {
            $old_password = trim($this->request->param('old_password'));
            $new_password = trim($this->request->param('new_password'));
            $confirm_password = trim($this->request->param('confirm_password'));
            if (empty($old_password)) {
                $this->error(lang('Please enter your old password'));
            }
            if (empty($new_password)) {
                $this->error(lang('Please enter a new password'));
            }
            if (empty($confirm_password)) {
                $this->error(lang('Please enter a confirmation password'));
            }
            if (!password_verify($old_password, $this->userInfo->password)) {
                $this->error(lang('The old password entered is incorrect'));
            }
            if ($new_password !== $confirm_password) {
                $this->error(lang('The confirmation password entered is incorrect'));
            }
            $this->userInfo->password = password_hash($confirm_password, PASSWORD_BCRYPT);
            if ($this->userInfo->save()) {
                $this->returnData['msg'] = lang('Password modification successful, please log in again');
                $this->returnData['code'] = 1;
            }

            $this->success();
        }

        return $this->view->fetch('user/reset_password');
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        if ($this->request->isPost()) {
            $user = $this->model::find($id);
            $user->delete();
            $this->returnData['code'] = 1;
            $this->success(lang('Done'));
        }

        $this->error();
    }
}
